services:
  caddy:
    image: caddy:2.8
    restart: unless-stopped
    ports: ["80:80","443:443"]
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./pwa:/srv/pwa:ro

  kernel:
    build: { context: ./app }
    restart: unless-stopped
    ports: ["8000:8000"]
    environment:
      - GPT_URL=${GPT_URL}
      - GPT_BEARER=${GPT_BEARER}
      - APPLET_STUB=${APPLET_STUB}

  applet:
    build: { context: ./applet }
    restart: unless-stopped
    ports: ["9001:9001"]
    environment:
      - GPT_URL=${GPT_URL}
      - GPT_BEARER=${GPT_BEARER}
      - APPLET_STUB=${APPLET_STUB}
